# Generated by Django 2.1.2 on 2019-02-01 02:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_auto_20190201_0218'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_pre_principal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payment_ipd', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payment_interest_paid', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payment_principal_paid', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payment_post_principal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.Loan')),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.date(2019, 2, 1)),
        ),
    ]
