# Generated by Django 2.1.2 on 2019-02-01 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20190201_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttracker',
            name='payment_date',
            field=models.DateField(default=datetime.date(2019, 2, 1)),
        ),
    ]
