# Generated by Django 2.1.2 on 2019-01-31 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_loan',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
