# Generated by Django 2.1.2 on 2019-01-30 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(max_length=100, unique=True)),
                ('loan_start_date', models.DateField(default=datetime.date(2019, 1, 30))),
                ('loan_starting_principal', models.DecimalField(decimal_places=2, max_digits=9)),
                ('loan_principal', models.DecimalField(decimal_places=2, max_digits=9)),
                ('loan_interest', models.DecimalField(decimal_places=4, max_digits=5)),
                ('loan_amort_months', models.IntegerField()),
            ],
        ),
    ]
